github: Prajwal-Koirala
patreon:
open_collective:
ko_fi: prajwalkoirala23
tidelift:
community_bridge:
liberapay: prajwalkoirala23
issuehunt: prajwal-koirala
otechie:
custom: paypal.me/prajwalkoirala23
